; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

default_envs = d1_mini

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
board_build.ldscript = eagle.flash.4m1m.ld
board_build.filesystem = littlefs
build_flags =
    "-D DEBUG_ESP_PORT=Serial"

monitor_speed = 115200
lib_deps = ArduinoJson, SPI, WiFiManager, DoubleResetDetector, https://github.com/adafruit/Adafruit_HTU21DF_Library, Adafruit GFX Library

[env:native]
platform = native
targets = test
test_framework = unity
test_build_src = yes
build_src_filter =
    +<DSTEurope.cpp>
    +<HumidityMath.cpp>
    +<SensorSanity.cpp>

