#pragma once

#include <Arduino.h>

#define FIRMWAREVERSION "0.9.1"
#define HOSTNAME "wetter"
#define OLED_RESET D3
#define RECEIVER_PIN D6

#define MIN_DIFF 3.0f
#define MIN_RECEIVE_WAIT_INT 2
#define MIN_RECEIVE_WAIT_EXT 200
#define MAX_RECEIVE_WAIT_EXT (120 * 1000)
#define MAX_RECEIVE_WAIT_EXT_S (MAX_RECEIVE_WAIT_EXT / 1000)
#define DEFAULT_NTP_SERVER "pool.ntp.org"
#define DEFAULT_TIMEZONE_POSIX "CET-1CEST,M3.5.0,M10.5.0/3"

#define OFFSET 1
#define DEFAULT_TEMP_OFFSET_INDOOR 1.0f

#define DRD_TIMEOUT 2
#define DRD_ADDRESS 0
